update cnio.fault_workorder set order_code  = cast(to_char(order_date, 'YYYYMMDD') || case
                    when fault_catalog ='小区类'  then '1'
                    when fault_catalog ='区域类'  then '0'
                    when fault_catalog ='小区对'  then '2' else '3' end || case
                    when fault_class ='覆盖控制'  then '0'
                    when fault_class ='业务体验'  then '1'
                    when fault_class ='工程质量'  then '2' 
                    when fault_class ='工程质量'  then '3' else '4' end || case
                    when fault_subclass = '弱覆盖'  then '1'
                    when fault_subclass ='重叠覆盖'  then '2'
                    when fault_subclass ='模三干扰'  then '3'
                    when fault_subclass ='异常事件'  then '4' 
                    when fault_subclass = '疑似天馈接反小区' then '5'
                    when fault_subclass = '疑似位置错误小区' then '6'
                    when fault_subclass = '疑似室分泄漏小区' then '7'
                    when fault_subclass = '疑似天线波瓣角异常小区' then '8'
                    when fault_subclass = '疑似天线方向角错误小区' then '9'
                    when fault_subclass = '越区覆盖小区' then '10'
                    when fault_subclass = '高重建比例小区' then '11'
                    when fault_subclass = '高切换失败小区对' then '12' else '0' end || order_id as int8 ) where order_code is null
